apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "ploutus.fullname" . }}
  labels:
{{ include "ploutus.labels" . | indent 4 }}
spec:
  schedule: "*/5 * * * *"
  backoffLimit: 4
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ include "ploutus.name" . }}
            app.kubernetes.io/instance: {{ .Release.Name }}
        spec:
          restartPolicy: OnFailure
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              resources:
    {{ toYaml .Values.resources | indent 16 }}
        {{- with .Values.nodeSelector }}
          nodeSelector:
    {{ toYaml . | indent 12 }}
        {{- end }}
        {{- with .Values.affinity }}
          affinity:
    {{ toYaml . | indent 12 }}
        {{- end }}
        {{- with .Values.tolerations }}
          tolerations:
    {{ toYaml . | indent 12 }}
        {{- end }}
